name: Publish NPM package

on:
  push:
    branches: ["publish"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run dist
      - run: npm publish 
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_PUBLISH_TOKEN }}"